{
    'name': 'Optimo Fiscal',
    'author': 'OPTESIS SA',
    'version': '1.2.5',
    'category': 'Asset',
    'description': """
Ce Module décrit les fonctionnalités mises en place pour l’intégration du calcul automatique de la Contribution Economique Local sur la Valeur Locative (CEL VL) dans Optimo. 
""",
    'summary': 'Module de Calcul de CEL VEL ',
    'sequence': 9,
    'depends': ['base','optimo','report_xlsx'],
    'data': [
     # 'security/security.xml',
      'security/ir.model.access.csv',
      #'security/multi_company_view.xml',
      #'datas/ir.cron.optimo.xml',
      #'datas/sequence_immo.xml',
      #'datas/sequence_control.xml',
      #'datas/sequence_transfert.xml',
      #'views/asset.xml',
      'views/inherit_view.xml',
      'report/report_etat_cel_vl.xml',
      'report/main_report.xml',
      'report/optesis_cel_header_view.xml',
      'report/optesis_external_layout.xml',
      'report/optesis_cel_declaration.xml',
      'report/custom_format.xml',
      'report/report.xml',
      #'views/organisation.xml',
      #'views/catalogue.xml',
      #'views/transfert.xml',
      #'views/res_config_settings_views.xml',
      #'wizards/wizard_message_view.xml',
      #'reports/fiche_detenteur_header_view.xml',
      #'reports/fiche_immobilisation_header_view.xml',
      #'reports/fiche_immobilisation_external_layout_header.xml',
      #'reports/fiche_detenteur_external_layout_header.xml',
      #'reports/report.xml',
      #'reports/fiche_detenteur.xml',
      #'reports/fiche_immobilisation.xml',
    ],
    'test': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
